### ISSUE TITLE
Mailgun does not show correct URL in integration

### ISSUE THREAD

**Issue by stlorenz** [kanboard/plugin-mailgun#10]
Hi,

Version 1.0.29 of kanboard dropped the Webhook-Support for creating tasks. 
We used this in conjuction with the mailgun plugin so far. 

After updating the mailgun settings still show 
````
https://mydomain.com/?controller=WebhookController&action=receiver&plugin=mailgun&token=XXX
````
instead of:
````
http://my_kanboard_domain.tld/mailgun/handler/XXXXX
`````

which is described in the documentation

Template/integration.php also reflects this:

````
  <input type="text" class="auto-select" readonly="readonly" value="<?= $this->url->href('WebhookController', 'receiver', array('plugin' => 'mailgun', 'token' => $values['webhook_token']), false, '', true) ?>">
````

Did we miss something in the upgrade process? 

Thanks in advance

**Comment by fguillot** [comment]
You will see the rewritten URL only if the URL rewriting is enabled and configured otherwise it fallback to query strings URL.

See https://kanboard.net/documentation/nice-urls

**Comment by stlorenz** [comment]
Thanks for the fast help in this issue. The now get routed fine but now the server responds with:

````
 *41 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/kanboard/plugins/Mailgun/vendor/league/html-to-markdown/src/HtmlConverter.php:101
Stack trace:
#0 /var/www/kanboard/plugins/Mailgun/vendor/league/html-to-markdown/src/HtmlConverter.php(76): League\HTMLToMarkdown\HtmlConverter->createDOMDocument('<html xmlns:v="...')
#1 /var/www/kanboard/plugins/Mailgun/EmailHandler.php(132): League\HTMLToMarkdown\HtmlConverter->convert('<html xmlns:v="...')
#2 /var/www/kanboard/plugins/Mailgun/EmailHandler.php(65): Kanboard\Plugin\Mailgun\EmailHandler->getDescription(Array)
#3 /var/www/kanboard/plugins/Mailgun/Controller/WebhookController.php(26): Kanboard\Plugin\Mailgun\EmailHandler->receiveEmail(Array)
#4 /var/www/kanboard/app/Core/Controller/Runner.php(77): Kanboard\Plugin\Mailgun\Controller\WebhookController->receiver()
#5 /var/www/kanboard/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController()
#6 /var/www/kanboard/index.php(9): Kanboard\Core\Cont" while reading response header from upstream, client: 172.16.12.1, server: kanboard.domain.de, request: "POST /mailgun/handler/XXXXX HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "kanboard.domain.de"
````

**Comment by fguillot** [comment]
The DOM PHP extension is missing, you have to install it on your system. On Ubuntu/Debian, it should be php-xml or php5.6-xml depending the version your are using.

The documentation should be updated as well.

**Comment by stlorenz** [comment]
Thanks again,. Now everything is working as expected.
